name: Laravel Tests

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupération complète du dépôt
      - name: Checkout full repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2️⃣ Vérification de la structure
      - name: Show repository structure
        run: ls -la && ls -la ./S5DevBack/DevLaravel/

      # 3️⃣ Configuration de PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, pdo, pdo_sqlite, bcmath
          coverage: none

      # 4️⃣ Installation des dépendances via Composer
      - name: Install dependencies
        run: |
          composer install --no-progress --prefer-dist --optimize-autoloader
        working-directory: ./S5DevBack/DevLaravel

      # 5️⃣ Configuration de l'environnement
      - name: Set environment
        run: cp .env.testing .env
        working-directory: ./S5DevBack/DevLaravel

      # 6️⃣ Génération de la clé d'application
      - name: Generate application key
        run: php artisan key:generate
        working-directory: ./S5DevBack/DevLaravel

      # 7️⃣ Exécution des migrations
      - name: Run migrations
        run: php artisan migrate --env=testing
        working-directory: ./S5DevBack/DevLaravel

      # 8️⃣ Lancement des tests
      - name: Run Unit Tests
        run: php artisan test --testsuite=Unit --parallel
        working-directory: ./S5DevBack/DevLaravel

      - name: Run Feature Tests
        run: php artisan test --testsuite=Feature --parallel
        working-directory: ./S5DevBack/DevLaravel
