name: Laravel Tests

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, pdo, pdo_sqlite, bcmath
          coverage: none

      - name: Install dependencies
        run: |
          composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Set environment
        run: cp .env.testing .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run Unit Tests
        run: php artisan test --testsuite=Unit --parallel

      - name: Run Feature Tests
        run: php artisan test --testsuite=Feature --parallel
